sudo: false
language: node_js
notifications:
  email: false
install: true
branches:
  only:
    - master
    - develop
before_deploy:
  - "echo 'Deploying on NPM ...'"
deploy:
  provider: npm
  email: dominique.m.mueller@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    branch: master
    repo: dominique-mueller/angular2-notifier
after_deploy:
  - "echo 'Done.'"
